-- MySQL Script generated by MySQL Workbench
-- 03/20/17 20:26:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema products
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema products
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `products` DEFAULT CHARACTER SET utf8 ;
USE `products` ;

-- -----------------------------------------------------
-- Table `products`.`Proizvodi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products`.`Proizvodi` (
  `Proizvod ID` INT NOT NULL,
  `Naziv proizvoda` VARCHAR(30) NOT NULL,
  `Opis proizvoda` VARCHAR(1000) NOT NULL,
  `Cijena` DOUBLE NOT NULL,
  `Slika` VARCHAR(50) NOT NULL,
  `Autor ID` INT NOT NULL,
  `Aktivan` INT NOT NULL,
  PRIMARY KEY (`Proizvod ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`.`Programi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products`.`Programi` (
  `ProgramID` INT NOT NULL,
  `Naziv programa` VARCHAR(45) NOT NULL,
  `Opis programa` VARCHAR(1000) NOT NULL,
  `AutorID` INT NOT NULL,
  `Aktivan` INT NOT NULL,
  PRIMARY KEY (`ProgramID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`.`Narudzbe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products`.`Narudzbe` (
  `NarudzbaID` INT NOT NULL,
  `Datum` DATETIME NOT NULL,
  `KorisnikID` INT NOT NULL,
  `ProdavacID` INT NOT NULL,
  `Aktivan` INT NOT NULL,
  PRIMARY KEY (`NarudzbaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`.`Stavke narudzbe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products`.`Stavke narudzbe` (
  `NarudzbaID` INT NOT NULL,
  `ProizvodID` INT NOT NULL,
  PRIMARY KEY (`NarudzbaID`, `ProizvodID`),
  INDEX `ProizvodID_idx` (`ProizvodID` ASC),
  CONSTRAINT `NarudzbaID_FK`
    FOREIGN KEY (`NarudzbaID`)
    REFERENCES `products`.`Narudzbe` (`NarudzbaID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `ProizvodID_FK_StavkeNarudzbe`
    FOREIGN KEY (`ProizvodID`)
    REFERENCES `products`.`Proizvodi` (`Proizvod ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`.`Stavke programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products`.`Stavke programa` (
  `ProgramID` INT NOT NULL,
  `ProizvodID` INT NOT NULL,
  PRIMARY KEY (`ProgramID`, `ProizvodID`),
  INDEX `ProizvodID_idx` (`ProizvodID` ASC),
  CONSTRAINT `ProgramID_FK`
    FOREIGN KEY (`ProgramID`)
    REFERENCES `products`.`Programi` (`ProgramID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `ProizvodID_FK_StavkePrograma`
    FOREIGN KEY (`ProizvodID`)
    REFERENCES `products`.`Proizvodi` (`Proizvod ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
